FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

#RUN mkdir -p /var/cache/nginx /var/run \
 # && chown -R nginx:nginx /var/cache/nginx /var/run /etc/nginx

#USER nginx

#EXPOSE 8080

#CMD ["nginx", "-g", "daemon off;"]
